name: Run tests

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ 7.4, 8.0 ]
    steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      run: vendor/bin/codecept run
